create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  user_id text not null,
  anime_id text not null,
  provider text not null default 'anilist',
  episode_id text not null,
  source text,
  position double precision not null default 0,
  duration double precision not null default 0,
  completed boolean not null default false,
  anime_title text,
  anime_cover text,
  episode_number integer,
  episode_title text,
  updated_at bigint not null
);

create unique index if not exists watch_history_user_anime_episode_source_key
  on public.watch_history (user_id, anime_id, provider, episode_id, source);

create index if not exists watch_history_user_updated_at_idx
  on public.watch_history (user_id, updated_at desc);

create table if not exists public.favorites (
  user_id text not null,
  anime_id text not null,
  provider text not null default 'anilist',
  anime_title text,
  anime_cover text,
  added_at bigint not null,
  primary key (user_id, anime_id, provider)
);

create index if not exists favorites_user_added_at_idx
  on public.favorites (user_id, added_at desc);

create table if not exists public.app_settings (
  user_id text not null,
  key text not null,
  value text not null,
  primary key (user_id, key)
);

create table if not exists public.trackers (
  user_id text not null,
  provider text not null,
  connected boolean not null default false,
  username text,
  token text,
  updated_at bigint not null,
  primary key (user_id, provider)
);
