-- ============================================
-- MeMo App - Complete Database Schema
-- ============================================
-- This schema includes all tables needed for:
-- - Watch history & progress tracking
-- - Continue watching functionality
-- - Favorites management
-- - User settings
-- - External tracker connections (MAL, Kitsu, AniList)
-- ============================================

-- Drop existing tables if they exist (for clean reinstall)
DROP TABLE IF EXISTS public.watch_history CASCADE;
DROP TABLE IF EXISTS public.favorites CASCADE;
DROP TABLE IF EXISTS public.app_settings CASCADE;
DROP TABLE IF EXISTS public.trackers CASCADE;

-- ============================================
-- WATCH HISTORY TABLE
-- ============================================
-- Tracks user's watch progress for each episode
-- Supports multiple providers (anilist, mal, kitsu)
-- Supports multiple sources (different streaming servers)
-- ============================================

CREATE TABLE public.watch_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- User & Anime identification
  user_id TEXT NOT NULL,
  anime_id TEXT NOT NULL,
  provider TEXT NOT NULL DEFAULT 'anilist',
  
  -- Episode identification
  episode_id TEXT NOT NULL,
  episode_number INTEGER,
  episode_title TEXT,
  
  -- Anime metadata (for display without additional API calls)
  anime_title TEXT,
  
  -- Streaming source (server name: kaa-manifest, kaido, gojowtf, etc.)
  -- This tells which server successfully streamed this episode
  source TEXT NOT NULL DEFAULT 'default',
  
  -- Progress tracking
  position DOUBLE PRECISION NOT NULL DEFAULT 0,
  duration DOUBLE PRECISION NOT NULL DEFAULT 0,
  completed BOOLEAN NOT NULL DEFAULT false,
  
  -- Timestamps
  updated_at BIGINT NOT NULL,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000
);

-- Unique constraint: one progress entry per user+anime+episode+source combination
CREATE UNIQUE INDEX watch_history_user_anime_episode_source_key
  ON public.watch_history (user_id, anime_id, provider, episode_id, source);

-- Index for fast "continue watching" queries (most recent incomplete episodes)
CREATE INDEX watch_history_user_updated_at_idx
  ON public.watch_history (user_id, updated_at DESC);

-- Index for fast anime-specific history queries
CREATE INDEX watch_history_user_anime_idx
  ON public.watch_history (user_id, anime_id, provider);

-- Index for completed episodes queries
CREATE INDEX watch_history_completed_idx
  ON public.watch_history (user_id, completed, updated_at DESC);

-- Index for server/source queries (find which servers work for an anime)
CREATE INDEX watch_history_anime_source_idx
  ON public.watch_history (anime_id, provider, source);

-- ============================================
-- FAVORITES TABLE
-- ============================================
-- Stores user's favorite anime
-- ============================================

CREATE TABLE public.favorites (
  -- User & Anime identification
  user_id TEXT NOT NULL,
  anime_id TEXT NOT NULL,
  provider TEXT NOT NULL DEFAULT 'anilist',
  
  -- Anime metadata (for display without additional API calls)
  anime_title TEXT,
  anime_cover TEXT,
  
  -- Timestamps
  added_at BIGINT NOT NULL,
  
  PRIMARY KEY (user_id, anime_id, provider)
);

-- Index for fast favorites list queries (most recent first)
CREATE INDEX favorites_user_added_at_idx
  ON public.favorites (user_id, added_at DESC);

-- Additional indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_anime_id ON favorites(anime_id);

-- ============================================
-- APP SETTINGS TABLE
-- ============================================
-- Stores user preferences and app settings
-- Key-value store for flexibility
-- ============================================

CREATE TABLE public.app_settings (
  user_id TEXT NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  updated_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,
  
  PRIMARY KEY (user_id, key)
);

-- Common settings keys:
-- - theme: 'light' | 'dark' | 'auto'
-- - autoplay_next: 'true' | 'false'
-- - skip_intro: 'true' | 'false'
-- - skip_outro: 'true' | 'false'

-- Subtitle settings (stored as JSON string):
-- - subtitle_font_size: number (14-24)
-- - subtitle_background_opacity: number (0-1)
-- - subtitle_text_color: string (hex color)
-- - subtitle_background_color: string (hex color)
-- - subtitle_position: 'top' | 'center' | 'bottom'
-- - subtitle_enabled: 'true' | 'false'

-- ============================================
-- TRACKERS TABLE
-- ============================================
-- Stores connections to external anime tracking services
-- (MyAnimeList, Kitsu, AniList)
-- ============================================

CREATE TABLE public.trackers (
  user_id TEXT NOT NULL,
  provider TEXT NOT NULL, -- 'mal' | 'kitsu' | 'anilist'
  
  -- Connection status
  connected BOOLEAN NOT NULL DEFAULT false,
  username TEXT,
  
  -- OAuth tokens (encrypted in production)
  token TEXT,
  refresh_token TEXT,
  token_expires_at BIGINT,
  
  -- Sync settings
  auto_sync BOOLEAN DEFAULT true,
  last_synced_at BIGINT,
  
  -- Timestamps
  updated_at BIGINT NOT NULL,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,
  
  PRIMARY KEY (user_id, provider)
);

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Function to get which servers/sources work for a specific anime
-- Returns list of servers that successfully streamed episodes
CREATE OR REPLACE FUNCTION get_working_servers_for_anime(
  p_user_id TEXT,
  p_anime_id TEXT,
  p_provider TEXT DEFAULT 'anilist'
)
RETURNS TABLE (
  source TEXT,
  episode_count BIGINT,
  last_used_at BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    wh.source,
    COUNT(DISTINCT wh.episode_id) as episode_count,
    MAX(wh.updated_at) as last_used_at
  FROM public.watch_history wh
  WHERE wh.user_id = p_user_id
    AND wh.anime_id = p_anime_id
    AND wh.provider = p_provider
  GROUP BY wh.source
  ORDER BY last_used_at DESC;
END;
$$ LANGUAGE plpgsql;

-- Function to get continue watching list (incomplete episodes)
CREATE OR REPLACE FUNCTION get_continue_watching(
  p_user_id TEXT,
  p_limit INTEGER DEFAULT 24
)
RETURNS TABLE (
  anime_id TEXT,
  episode_id TEXT,
  episode_number INTEGER,
  provider TEXT,
  source TEXT,
  watch_position DOUBLE PRECISION,
  duration DOUBLE PRECISION,
  updated_at BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT ON (wh.anime_id, wh.provider)
    wh.anime_id,
    wh.episode_id,
    wh.episode_number,
    wh.provider,
    wh.source,
    wh.position as watch_position,
    wh.duration,
    wh.updated_at
  FROM public.watch_history wh
  WHERE wh.user_id = p_user_id
    AND wh.completed = false
    AND wh.position > 0
    AND wh.position < wh.duration * 0.95
  ORDER BY wh.anime_id, wh.provider, wh.updated_at DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;

-- Function to get completed anime
CREATE OR REPLACE FUNCTION get_completed_anime(
  p_user_id TEXT,
  p_limit INTEGER DEFAULT 60
)
RETURNS TABLE (
  anime_id TEXT,
  episode_id TEXT,
  episode_number INTEGER,
  provider TEXT,
  updated_at BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT ON (wh.anime_id, wh.provider)
    wh.anime_id,
    wh.episode_id,
    wh.episode_number,
    wh.provider,
    wh.updated_at
  FROM public.watch_history wh
  WHERE wh.user_id = p_user_id
    AND wh.completed = true
  ORDER BY wh.anime_id, wh.provider, wh.updated_at DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================
-- Enable RLS to ensure users can only access their own data
-- ============================================

-- Enable RLS on all tables
ALTER TABLE public.watch_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trackers ENABLE ROW LEVEL SECURITY;

-- Watch History Policies
CREATE POLICY "Users can view their own watch history"
  ON public.watch_history FOR SELECT
  USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert their own watch history"
  ON public.watch_history FOR INSERT
  WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can update their own watch history"
  ON public.watch_history FOR UPDATE
  USING (auth.uid()::text = user_id);

CREATE POLICY "Users can delete their own watch history"
  ON public.watch_history FOR DELETE
  USING (auth.uid()::text = user_id);

-- Favorites Policies
CREATE POLICY "Users can view their own favorites"
  ON public.favorites FOR SELECT
  USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert their own favorites"
  ON public.favorites FOR INSERT
  WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can update their own favorites"
  ON public.favorites FOR UPDATE
  USING (auth.uid()::text = user_id);

CREATE POLICY "Users can delete their own favorites"
  ON public.favorites FOR DELETE
  USING (auth.uid()::text = user_id);

-- App Settings Policies
CREATE POLICY "Users can view their own settings"
  ON public.app_settings FOR SELECT
  USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert their own settings"
  ON public.app_settings FOR INSERT
  WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can update their own settings"
  ON public.app_settings FOR UPDATE
  USING (auth.uid()::text = user_id);

CREATE POLICY "Users can delete their own settings"
  ON public.app_settings FOR DELETE
  USING (auth.uid()::text = user_id);

-- Trackers Policies
CREATE POLICY "Users can view their own trackers"
  ON public.trackers FOR SELECT
  USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert their own trackers"
  ON public.trackers FOR INSERT
  WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can update their own trackers"
  ON public.trackers FOR UPDATE
  USING (auth.uid()::text = user_id);

CREATE POLICY "Users can delete their own trackers"
  ON public.trackers FOR DELETE
  USING (auth.uid()::text = user_id);

-- ============================================
-- SAMPLE DATA (Optional - for testing)
-- ============================================
-- Uncomment to insert sample data for testing
-- ============================================

-- INSERT INTO public.app_settings (user_id, key, value) VALUES
--   ('test-user-id', 'theme', 'dark'),
--   ('test-user-id', 'autoplay_next', 'true'),
--   ('test-user-id', 'skip_intro', 'true'),
--   ('test-user-id', 'subtitle_settings', '{"fontSize":17,"backgroundOpacity":0.8,"textColor":"#FFFFFF","backgroundColor":"#000000","enabled":true}');

-- ============================================
-- SCHEMA COMPLETE
-- ============================================
-- Run this entire file in Supabase SQL Editor
-- Then restart your backend server
-- ============================================
